---
- name: buildout | add .buildout directory
  file:
    path: "{{ homepath }}/.buildout"
    owner: "{{ username }}"
    group: "{{ username }}"
    state: directory

- name: buildout | add default.cfg file
  template:
    src: "templates/default.cfg"
    dest: "{{ homepath }}/.buildout/default.cfg"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755
