---
- name: chromium | add ppa repository
  apt_repository:
    repo: 'ppa:canonical-chromium-builds/stage'
    state: present
    update_cache: yes
  become: yes
  become_user: root

- name: chromium | install
  apt:
    name: chromium-browser
    state: latest
  become: yes
  become_user: root
