---
- name: docker | install package dependency
  apt: pkg={{ item }} state=present update_cache=yes
  become: yes
  tags: packages
  with_items:
    - apt-transport-https
    - ca-certificates
    # - curl
    # - software-properties-common

- name: docker | add Docker repository key
  shell: "curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -"

# lsb_release -cs
- name: docker | set stable repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu zesty stable"
    update_cache: yes

- name: docker | install (or update) docker package
  apt:
    name: "docker-ce"
    state: "latest"

- name: docker | start
  service:
    name: docker
    state: started

# ATTENTION: this task can potentially create new users!
- name: docker | add user to the docker group
  user:
    name:   "{{ username }}"
    groups: docker
    append: yes

- name: docker | installing docker compose
  pip:
    name: docker-compose
    state: latest
