---
- name: git | add .gitconfig file
  template:
    src: "templates/.gitconfig"
    dest: "{{ homepath }}/.gitconfig"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755


- name: git | add .gitignore file
  template:
    src: "templates/.gitignore"
    dest: "{{ homepath }}/.gitignore"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755


- name: git | link init ignore to Dropbox
  file:
    src: "{{ homepath }}/Dropbox/config/ignore"
    dest: "{{ homepath }}/.ignore"
    owner: "{{ username }}"
    group: "{{ username }}"
    state: link
  become: yes
  become_user: "{{ username }}"
  tags: nvim
