---
- name: git | add .gitconfig file
  template:
    src: "templates/.gitconfig"
    dest: "{{ homepath }}/.gitconfig"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755


- name: git | add .gitignore file
  template:
    src: "templates/.gitignore"
    dest: "{{ homepath }}/.gitignore"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755
