---
- name: Common | Install package utilities
  apt: pkg={{ item }} state=present update_cache=yes
  become: yes
  tags: packages
  with_items:
   - curl
   - htop
   - tig
   - apt-utils

- include: keys.yml
- include: ssh.yml
- include: git.yml
- include: vim.yml
- include: atom.yml
- include: zsh.yml
