---
- name: common | install package utilities
  apt: pkg={{ item }} state=present update_cache=yes
  become: yes
  tags: packages
  with_items:
   - apt-utils
   - curl
   - htop
   - openssh-server
   - openvpn
   - network-manager-openvpn
   - network-manager-openvpn-gnome
   - tig
   - wget
   - diodon
   - net-tools
   - lynx
   - shutter
   # needed for rvm
   - libaugeas-dev
   - dnsmasq
   - libncurses5-dev
   - graphviz

- name: common | install package used to gnome shell
  apt: pkg={{ item }} state=present update_cache=yes
  become: yes
  tags: packages
  with_items:
   - gir1.2-gtop-2.0
   - gir1.2-networkmanager-1.0
   - gir1.2-clutter-1.0

- include: ssh.yml
- include: atom.yml
- include: buildout.yml
- include: chromium.yml
- include: docker.yml
- include: eid.yml
- include: git.yml
- include: lastpass.yml
- include: plone.yml
- include: pythons.yml
- include: slack.yml
- include: vim.yml
- include: wifi.yml
- include: yubikey.yml
- include: virtualbox.yml
- include: zsh.yml
