---
- name: common | install package utilities
  apt: pkg={{ item }} state=present update_cache=yes
  become: yes
  tags: packages
  with_items:
   - apt-utils
   - curl
   - htop
   - openssh
   - tig
   - wget

- include: atom.yml
- include: buildout.yml
- include: chromium.yml
- include: git.yml
- include: lastpass.yml
- include: plone.yml
- include: pythons.yml
- include: rvm.yml
- include: slack.yml
- include: ssh.yml
- include: vim.yml
- include: yubikey.yml
- include: zsh.yml
