---

- name: plone | install package needed by Zope/Plone
  apt: pkg={{ item }} state=present update_cache=yes
  become: yes
  tags:
   - packages
   - plone
  with_items:
   - build-essential
   - libbz2-dev
   - libjpeg62-dev
   - libpcre3
   - libpcre3-dev
   - libreadline-gplv2-dev
   - libssl-dev
   - libxml2-dev
   - libxslt1-dev
   - poppler-utils
   - python-dev
   - python-virtualenv
   - wv

- name: plone | install packages needed by Pillow
  apt: pkg={{ item }} state=present update_cache=yes
  become: yes
  tags:
   - packages
   - plone
  with_items:
   - libfreetype6-dev
   - libjpeg8-dev
   - liblcms2-dev
   - libtiff5-dev
   - libwebp-dev
   - tcl8.6-dev
   - tk8.6-dev
   - zlib1g-dev

# robot
- name: plone | download the gecko driver
  get_url: url="https://github.com/mozilla/geckodriver/releases/download/v{{ gecko_version }}/geckodriver-v{{ gecko_version }}-linux64.tar.gz" dest=/tmp mode=0777
  tags:
   - plone
   - geckodriver

- name: plone | install the gecko driver
  unarchive:
    src: "/tmp/geckodriver-v{{ gecko_version }}-linux64.tar.gz"
    dest: "/usr/local/bin/"
    mode: 0775
    copy: no
    owner: "{{ username }}"
    group: "{{ username }}"
  tags:
   - plone
   - geckodriver
