---
- name: pythons | install some python packages
  apt: pkg={{ item }} state=present update_cache=yes
  become: yes
  tags:
   - packages
   - pythons
  with_items:
   - build-essential
   - python-pip
   - python-virtualenv

- name: pythons | set good owner of /opt
  file:
    path: "/opt"
    owner: "{{ username }}"
    group: "{{ username }}"
    state: directory
  tags: pythons

- name: pythons | python-tools | update/clone python-tools repo
  git:
    repo: "git@github.com:bsuttor/python-tools.git"
    dest: "/opt/python-tools"
    accept_hostkey: yes
  become: yes
  become_user: "{{ username }}"
  tags: pythons

- name: pythons | python-tools | create venv
  command: virtualenv .
  args:
    chdir: /opt/python-tools
    creates: bin/pip
  become: yes
  become_user: "{{ username }}"
  tags: pythons

- name: pythons | python-tools | install buildout
  command: bin/pip install -r requirements.txt
  args:
    chdir: /opt/python-tools
    creates: bin/buildout
  become: yes
  become_user: "{{ username }}"
  tags: pythons

- name: pythons | python-tools | start buildout
  command: bin/buildout
  args:
    chdir: /opt/python-tools
    creates: bin/fullrelease
  become: yes
  become_user: "{{ username }}"
  tags: pythons

- name: pythons | .pypirc file
  file:
    src: "{{ homepath }}/Dropbox/config/pypirc"
    dest: "{{ homepath }}/.pypirc"
    owner: "{{ username }}"
    group: "{{ username }}"
    state: link
  tags: pythons

# - name: pythons | update/clone buildout-python repo
#   git:
#     repo: "git@github.com:collective/buildout.python.git"
#     dest: "/opt/pythons"
#     accept_hostkey: yes
#     update: no
#   become: yes
#   become_user: "{{ username }}"
#   tags: pythons

- name: pythons | set good owner of /opt
  file:
    path: "/opt/bin"
    owner: "{{ username }}"
    group: "{{ username }}"
    state: directory
  tags: pythons

# - name: pythons | link virtualenv-2.7
#   file:
#     src: "/opt/pythons/bin/virtualenv-2.7"
#     dest: "/usr/local/bin/virtualenv-2.7"
#     state: link
#     force: yes
#   tags: pythons
