---
- name: vim | package is installed
  apt: name=vim state=installed
  tags: vim

- name: vim | link vimrc to Dropbox
  file:
    src: "{{ homepath }}/Dropbox/config/vimrc"
    dest: "{{ homepath }}/.vimrc"
    owner: "{{ username }}"
    group: "{{ username }}"
    state: link
  become: yes
  become_user: "{{ username }}"

- name: vim | update/clone vundle
  git:
    repo: 'https://github.com/VundleVim/Vundle.vim.git'
    dest: "{{ homepath }}/.vim/bundle/vundle"
  become: yes
  become_user: "{{ username }}"

- name: vim | install vundle plugins
  shell: vim +PluginInstall +qall
  become: yes
  become_user: "{{ username }}"


- name: nvim | link init.vim to Dropbox
  file:
    src: "{{ homepath }}/Dropbox/config/init.vim"
    dest: "{{ homepath }}/.config/nvim/init.vim"
    owner: "{{ username }}"
    group: "{{ username }}"
    state: link
  become: yes
  become_user: "{{ username }}"
  tags: nvim


# See https://github.com/neovim/neovim/wiki/Installing-Neovim#ubuntu
- name: nvim | add ppa repository
  apt_repository:
    repo: 'ppa:canonical-chromium-builds/stage'
    state: present
    update_cache: yes
  become: yes
  become_user: root
  tags: nvim

- name: nvim | install package dependency
  apt: pkg={{ item }} state=present update_cache=yes
  become: yes
  with_items:
    - python-dev
    - python-pip
    - python3-dev
    - python3-pip
    - fzf
    - ripgrep
  tags:
    - packages
    - nvim

- name: nvim | install
  apt:
    name: neovim
    state: latest
  become: yes
  become_user: root
  tags: nvim

- name: nvim | install plug
  shell: curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  tags: nvim

 name: nvim | install Plug plugins
 shell: nvim +PlugInstall +qall
  become: yes
  become_user: "{{ username }}"


