---
- name: vim | package is installed
  apt: name=vim state=installed
  tags: vim

- name: vim | link vimrc to Dropbox
  file:
    src: "{{ homepath }}/Dropbox/config/vimrc"
    dest: "{{ homepath }}/.vimrc"
    owner: "{{ username }}"
    group: "{{ username }}"
    state: link

- name: vim | update/clone vundle
  git:
    repo: 'https://github.com/VundleVim/Vundle.vim.git'
    dest: "{{ homepath }}/.vim/bundle/Vundle.vim"

- name: vim | install vundle plugins
  shell: vim +PluginInstall +qall
