#!/bin/sh

export XKL_XMODMAP_DISABLE=1
unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS

[ -x /etc/vnc/xstartup ] && exec /etc/vnc/xstartup
[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources
xsetroot -solid grey
vncconfig -iconic &

gnome-panel &
gnome-settings-daemon &
metacity &
nautilus &
#This script customises and bugfixes gnome - it is being run here - rather than in .gnomerc or similar as these will not work with manausl launch - and the user is already logged in so we arn't using gdm or similar - this should be refactored to run sliently and lock user input/VNC output untill it has completed.
gnome-terminal -e /usr/local/etc/gnome-docker-fix-and-customise.sh &
